### PR TITLE
🚑 fix(web): refresh page avatars when updated

### LINKED ISSUE #43: when uploading avatar, storage server has error and new avatar not rendered on page
when uploading a new avatar, the upload does succeed and the image is accessible
but the avatar on the page does not refresh to new value

<details>
<summary>prev error (fixed)</summary>
the storage server logs out an error
```
@uninbox/storage:dev: [nitro] [uncaughtException] TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Object
@uninbox/storage:dev:     at write_ (node:_http_outgoing:879:11)
@uninbox/storage:dev:     at ServerResponse.end (node:_http_outgoing:1030:5)
@uninbox/storage:dev:     at Immediate.<anonymous> (file:///Users/omar/code/UnInbox/node_modules/.pnpm/h3@1.10.1/node_modules/h3/dist/index.mjs:682:24)
@uninbox/storage:dev:     at process.processImmediate (node:internal/timers:478:21) {
@uninbox/storage:dev:   code: 'ERR_INVALID_ARG_TYPE'
@uninbox/storage:dev: }
```

</details>
Error is fixed by https://github.com/uninbox/UnInbox/pull/48

### PR DESCRIPTION
**Pull request by skushagra9**
## What does this PR do?

Fixes #43 

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Required
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Tested my code in a local environment
- [ ] Commented on my code in hard-to-understand areas
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the UnInbox Docs if changes were necessary

### CODE REVIEW

File: apps/web-app/pages/[orgSlug]/settings/org/index.vue [hunk 1]
```diff
@@ -84,7 +84,8 @@
     }
 
     uploadLoading.value = false;
-
+    refreshNuxtData('getUserSingleProfileNav');
```
Comment (McPizza0) [inline apps/web-app/pages/[orgSlug]/settings/org/index.vue:87]: why is this here?
we only need to refresh the org profile since thats what we are changing

File: apps/web-app/pages/[orgSlug]/settings/user/profiles.vue [hunk 2]
```diff
@@ -99,8 +99,9 @@
         '5xl'
       );
     }
-
     uploadLoading.value = false;
+    refreshNuxtData('getUserSingleProfileNav');
+    refreshNuxtData('getUserOrgsNav');
```
Comment (McPizza0) [inline apps/web-app/pages/[orgSlug]/settings/user/profiles.vue:104]: why is this here?
we only need to refresh the user profile since thats what we are changing

File: apps/web-app/pages/join/profile.vue [hunk 3]
```diff
@@ -94,8 +94,9 @@
         '5xl'
       ) as string;
     }
-
     uploadLoading.value = false;
+    refreshNuxtData('getUserSingleProfileNav');
+    refreshNuxtData('getUserOrgsNav');
```
Comment (McPizza0) [inline apps/web-app/pages/join/profile.vue:99]: why are these here?
the data for them only loads when the user is in the app

**Review by McPizza0 — CHANGES_REQUESTED** [review]
you rushed into solving this
the primary issue is not resolved
please run the app locally and go through the user flow to understand the issue

**Comment by skushagra9** [comment]
ok , I will resolve it

**Comment by skushagra9** [comment]
I tested these changes in the feat/attatchment-upload branch and there its working fine but the the avatar on the page doesn't changes

**Comment by skushagra9** [comment]
I have added nuxtrefresh before the uploading.value = false to enhance userExperience

**Comment by skushagra9** [comment]
its failing with usefetch on another branch, adding $fetch

File: apps/web-app/pages/join/profile.vue [hunk 4]
```diff
@@ -94,7 +94,6 @@
         '5xl'
       ) as string;
     }
-
```
Comment (McPizza0) [inline apps/web-app/pages/join/profile.vue:97]: we should also do the same thing here, after upload set the image url to the returned avatarId

**Review by McPizza0 — CHANGES_REQUESTED** [review]

**Review by McPizza0 — APPROVED** [review]
